### ISSUE TITLE
Stop moving the right side when you hover the Navigation Minimap (Above Cargo Box)

### ISSUE THREAD

**Issue by Sei-lus** [Tsunder/Pardus-Sweetener#103]
**Describe the solution**
When you hover the minimap, it makes everything move downward (missions and cargo) which is annoying. I like that the sector name, coordinates and calculations aren't showed unless you hover, but can you set the div area where it spawns be there with the occupied space it needs?

Also, can you make it double liner?
Currently:
"Distance to Sector [0,0]: 500 APs"
Proposal:
"Distance to Sector {0,0]:
            500 APs"

With an align-text: center

Reasoning is problems with really long sector names like Eta Cassiopeia and Sigma Draconis

I have tried to do it myself but haven't figured a way.

**Comment by Tsunder** [comment]
addressed in #114 and #105 ?
