### ISSUE TITLE
Aware AP calculator

### ISSUE THREAD

**Issue by Tsunder** [Tsunder/Pardus-Sweetener#13]
minimap pather should be able to calculate the players current speed from the nav screen information

**Comment by BartKieviet** [comment]
I did this. See getSpeed my Sweetener Repo, from my map.js. 

The function is:
```		function getSpeed() {
			let current = this.getCurrentCoords();
			let currentTileType = this.sector.tiles[ current.col + this.sector.width * current.row ];
			let moveField = document.getElementById('tdStatusMove').childNodes;
			let speed = 0;
			if ( moveField.length > 1 ) { //something modifies our speed 
				speed -= parseInt( moveField[1].childNodes[0].textContent );
			}
			speed -= parseInt( moveField[0].textContent );
			speed += this.VISC[ currentTileType ];

			return speed;
		}````
Should work with minimal changes (VISC you don't use here I see)

**Comment by Tsunder** [comment]
neat.
I believe I copied it now.
Unfortunately I haven't looked at how the minimap pather works, as @likuilin wrote it.

**Comment by likuilin** [comment]
The navigation page doesn't reveal what level of Advanced Navigation the pilot is, though, and in my opinion imperfect detection < user-supplied values. That's why the options page has that table instead of just a ship drive dropdown or something.

**Comment by BartKieviet** [comment]
We could change the options to have user input on Nav, or store the Navigation level from the adv. skills page, which would result in a small discrepancy before the Adv. skills page is visited.

**Comment by Tsunder** [comment]
the fewer actions the player has to make, the better.
