### ISSUE TITLE
Add non-premium mission storage

### ISSUE THREAD

**Issue by BartKieviet** [Tsunder/Pardus-Sweetener#35]

**Comment by Tsunder** [comment]
almost there
transport missions might not be stacking properly - explosives missions seem to be considered packages.

**Comment by BartKieviet** [comment]
Explosives and packages are added up by design, only the first type you take is shown. Since it is stored per location instead of per type, only one mission type **can** be shown, since we don't store it.
This could be split up by saving amountPackages and amountExplosives in the object, but we'll have to split the mission up when parsing it on the nav screen.

**Comment by BartKieviet** [comment]
881c82b9c896d71b424cff677560db9ae56535a9
