### ISSUE TITLE
Ability to remove individual missions

### ISSUE THREAD

**Issue by Tsunder** [Tsunder/Pardus-Sweetener#36]
For when those explosives go boom, mostly.

An X maybe to remove?

Maybe takes up too much space, the mission display is already very dense.

**Comment by BartKieviet** [comment]
That's a tough one, since individual missions aren't stored per mission, but per location or per type.

**Comment by Tsunder** [comment]
mmm, and clearing the whole stack would well, not be ideal either.

explosives handling is tricky

**Comment by Tsunder** [comment]
clearing missions/refreshing entirely from job overview page does most of the functionality, and is kinda much to track anyway.

if you fail the explosives mission, you fail the explosives mission :P
