### ISSUE TITLE
mission target indicator doesn't show properly

### ISSUE THREAD

**Issue by Tsunder** [Tsunder/Pardus-Sweetener#44]
situation:
moving towards mission with a destination to a PSB

expected behaviour:
indicator dot appears on PSB

actual behaviour:
indicator dot disappears after moving, only shows on first load of page.

thoughts:
perhaps partial refresh is messing things up?

**Comment by BartKieviet** [comment]
perhaps the class is changed? The other dots do work, so the partial refresh should be accounted for.

**Comment by Tsunder** [comment]
somehow caused by #42 

putting navTable defining back into the same scope made it work for some reason. I don't like it and don't understand why at the moment.
