### ISSUE TITLE
Assassinate X number missions stack improperly

### ISSUE THREAD

**Issue by Tsunder** [Tsunder/Pardus-Sweetener#48]
Expected Behaviour:
Accepting a "kill 3 space maggot" mission and a "kill 4 space maggot" mission shows having a kill 3 space maggot mission, and a kill 4 space maggot mission.

Actual Behaviour:
Mission tracker displays having 2 kill "3 space maggot" missions, and will clear once three space maggots are killed.

**Comment by BartKieviet** [comment]
Again? I thought this was fixed in aebe403a676e05887953c484865fab2dbac0a4ec . It should do as follows: check if current amount done < new amount done and change amount done.
Perhaps it does not change the amount required if it's higher.

**Comment by BartKieviet** [comment]
Testing required though!

**Comment by Tsunder** [comment]
Seems to now reflect highest kills, but at the same time, a stack of 3 "kill 3 ice beasts" did not register any kills (stayed at 0/3), even when the 3rd IB was killed.

Will test with more logging.


So I'm thinking: Would it be "better" to store the kill # X's missions in the form of "Kill # more X's" and decrement the # as X's are killed? so taht it only shows and tracks the remaining to be killed rather than progress (number killed and total to be killed?)?

**Comment by Tsunder** [comment]
seems to now be showing multiple kill x's as just one mission.
i.e., have 2 jobs that are kill 3 ESD, nav display says there's only 1 kill 3 ESD job.
