### ISSUE TITLE
Functionality based on GM script "Pardus Coords Addon"

### ISSUE THREAD

**Issue by dsshad** [Tsunder/Pardus-Sweetener#52]
Hello,

I've been making a few suggestions / feature requests in the original valitas' repository, until I've found out, that this one is the actively developed one, so I would like to post my suggestions / wishes here as well.

This one is about the functionality based on the GM script "Pardus Coords Addon", which adds coordinates around the Pardus navigation grid and also draws grid lines on the navscreen, so that it looks like this:

![image](https://user-images.githubusercontent.com/43317663/53298708-02eb3500-3832-11e9-8917-c2d8ef55e25e.png)

The above screenshot is the result of a modified user script you can find here: https://openuserjs.org/scripts/Yog/Pardus_Coords_Addon

FYI: The linked script doesn't work with partial refresh (I'm not using partial refresh anyway).

What does not work with this script, is the path preview I used before (coming from an old extension, which also has been doing grid lines).

The path preview of the Sweetener works to some extent, but the whole navscreen becomes darker, once (i believe the second) tile is marked by the path preview. Here is how it looks then:

![image](https://user-images.githubusercontent.com/43317663/53298779-e00d5080-3832-11e9-98a4-b16d3245ad1b.png)

Plus the tiles with NPCs or buildings remain highlighted, when moving the mouse over them, even if the path has been moved away from them and these tiles wouldn't be visited anymore by the currently displayed path (see the highlighted TO and ISP on the second screenshot)

To show the different ‎brightness here a combined screenshot (on the right the darker part)
![image](https://user-images.githubusercontent.com/43317663/53298903-46df3980-3834-11e9-9f10-fbb67e479088.png)

It would be great, if this functionality would get integrated into Sweetener and refined to work with the path display and the functionality to highlight visited tiles for a certain time, for which I will make another request.

**Comment by dsshad** [comment]
A small addition: the screen becomes darker only when using the user script mentioned here. Another reason to integrate this gridlines and coords into sweetener, so that everything comes ‎from a single source.

**Comment by Tsunder** [comment]
now included as an option that's off by default
