### ISSUE TITLE
mission tracker bugs

### ISSUE THREAD

**Issue by Tsunder** [Tsunder/Pardus-Sweetener#58]
1. transports does not get the image correctly from non-premium bb or jobs
2. non-targeted critter (i.e., kill 1 SM) do not show as sticked (always shows as 1 mission)

**Comment by BartKieviet** [comment]
1. Can you be more specific? No the correct image or no list at all? Console errors? A single faction transport mission works on both pages for me.
2. Do the rewards add up? The only way this happens is if `locId` is not in the storage (see `Mission.updateMission`, the other two options have `mission.total += 1 `

**Comment by BartKieviet** [comment]
I also get a stack of non-target missions:
![image](https://user-images.githubusercontent.com/25323440/53692584-d6d03680-3d92-11e9-80fd-6878e04593cc.png)

**Comment by Tsunder** [comment]
looks like it was caused by me using a different branch.
