### ISSUE TITLE
splitting map data into visual and background?

### ISSUE THREAD

**Issue by Tsunder** [Tsunder/Pardus-Sweetener#76]
thoughts on splitting minimap into a visual - for display, data, and background, for path finding?

particularly, would like to split sectors like Pardus and Heze into various parts, similar to how Terpai / this tcc does it http://web.cs.elte.hu/~terpai/tcc_alt.html

main benefit I am looking at is being able to make a trivial check to see if the target tile is in the same "sector" as the user, instead of partially freezing the user's browser (more powerful than a stun TB)

**Comment by BartKieviet** [comment]
I'm working on this with the TCC too.
