### ISSUE TITLE
navigation area odd display

### ISSUE THREAD

**Issue by Tsunder** [Tsunder/Pardus-Sweetener#79]
**Describe the bug**
navigation area gets... weird.
the leftmost colums of tiles get a large separation between them, the space inbetween looks roughly as much as a tile width itself.

**To Reproduce**
1. Go to navigation
2. unknown

**Screenshots**
Will produce next time it occurs.

**Additional context**
at this time, unsure if caused by PST or anything else.

**Comment by BartKieviet** [comment]
![image](https://user-images.githubusercontent.com/25323440/54810116-89eeca00-4c85-11e9-8b21-4f1fe5ad29d9.png)
It happens after combat. It gets worse after more combats.

**Comment by BartKieviet** [comment]
Also happens after pressing `nav` after moving. Must be related to the partial refresh.
