### ISSUE TITLE
consumables clock inaccurate sometimes

### ISSUE THREAD

**Issue by Tsunder** [Tsunder/Pardus-Sweetener#95]
**Describe the bug**
Sometimes, the clock will show the pilot as clean despite them not being.
This leads to the pilot taking alternative comestibles while still under the influence.

**To Reproduce**
Take one type of comestibles.
After a while then take another type.

**Additional context**
Only happens rarely

**Comment by Tsunder** [comment]
some reporter saying it only occurs in artemis.
maybe artemis has different timer?

**Comment by Tsunder** [comment]
anecdotal reports that the drug tick in Artemis is on 29th minute instead of 59th minute.

**Comment by Sei-lus** [comment]
A bit bothered it is called "Anecdotal" when it can be tested easily.

Artemis and Orion have different tick times for drugs. Orion happens at :59 minutes, Artemis at :29 minutes.

How to reproduce?
Take Crimson/Amber/Capri Stim at :25 or :55 Minutes on any universe. Tick will happen at :29 and :59 for Stims so you can use Candies at the :35 or :05 Minute mark (respectively, the moment you take them after the Stim timer is unimportant... I use :35 or :05 for convenience)
This will prove that colored stims have a reset timer at :29 and :59 independent of the universe.
Now, do the opposite... Take 1t of Candy at :25 or at :55 then take Crimson/Amber/Capri Stim at :35 or at :05. The result will vary according to the universe.
Results:
Orion and Pegasus (Pegasus not directly tested by me)
1t of drug at :25, then 1t of colored stim at :35 will result in a message of "you are under the influence of..."
1t of drug at :55, then 1t of colored stim at :05 will result in a successful gain of APs for both.
Artemis
1t of drug at :55, then 1t of colored stim at :05 will result in a message of "you are under the influence of..."
1t of drug at :25, then 1t of colored stim at :35 will result in a successful gain of APs for both.

Also, you can use colored stims at 2 per hour without advance skills, effectively doubling the amount of regular stims you could use in a day.

**Comment by Tsunder** [comment]
seems good. another confirmed for artemis having 29 for drug tick instead of 59
devs why

I'm thinking will set the tick for artemis specifically to be 29 instead of 59. If the devs change the timings again will consider making a more robust system/easier to update, but for a single exception, a single exception should made.

> Also, you can use colored stims at 2 per hour without advance skills, effectively doubling the amount of regular stims you could use in a day.

Is this something different from taking 24t coloured stims twice a day 12ish hours apart? (This is getting slightly off topic)

**Comment by Sei-lus** [comment]
Not different. It is just that I'm new to the game and I got my game knowledge from "The Waistalands" page where it is is explicitly states you can take 24-25 stims a day.

You can take 24t twice a day yielding a total of 3600 APs gained.

Last thing off topic... I added a pull request but not sure if it was properly added to you Tsunder fork or the original. It was made for Sweetner T.
